import React from "react";

const useCityMasterConfig = () => {
    const cityListingColDef = [
        {
            id: "cityId",
            field: "cityId",
            headerName: "Id",
            width: 80,
        },
        {
            id: "countryName",
            field: "countryName",
            headerName: "Country",
            width: 180,
        },
        {
            id: "stateName",
            field: "stateName",
            headerName: "State",
            width: 180,
        },
        {
            id: "cityCode",
            field: "cityCode",
            headerName: "City Code",
            width: 130,
        },
        {
            id: "cityName",
            field: "cityName",
            headerName: "City Name",
            width: 220,
        },
        {
            id: "postalPrefix",
            field: "postalPrefix",
            headerName: "Postal Prefix",
            width: 140,
        },
        {
            id: "latitude",
            field: "latitude",
            headerName: "Latitude",
            width: 140,
        },
        {
            id: "longitude",
            field: "longitude",
            headerName: "Longitude",
            width: 140,
        },
    ];

    const citySchema = [
        {
            id: "countryId",
            type: "selectWrapper",
            label: "Country",
            placeHolder: "Select Country",
            required: true,
            nextFocusField: "stateId",
            className: "col-span-6",
            options: [
                { label: "India", value: 1 },
                { label: "United States", value: 2 },
                { label: "Canada", value: 3 },
            ],
        },
        {
            id: "stateId",
            type: "selectWrapper",
            label: "State",
            placeHolder: "Select State",
            required: true,
            prevFocusField: "countryId",
            nextFocusField: "cityCode",
            className: "col-span-6",
            options: [
                { label: "Gujarat", value: 1 },
                { label: "Maharashtra", value: 2 },
                { label: "Rajasthan", value: 3 },
            ],
        },
        {
            id: "cityCode",
            type: "text",
            label: "City Code",
            placeHolder: "AMD",
            required: true,
            prevFocusField: "stateId",
            nextFocusField: "cityName",
            className: "col-span-6",
            maxLength: 5,
            textTransform: "uppercase",
        },
        {
            id: "cityName",
            type: "text",
            label: "City Name",
            placeHolder: "Enter City Name",
            required: true,
            prevFocusField: "cityCode",
            nextFocusField: "postalPrefix",
            className: "col-span-6",
        },
        {
            id: "postalPrefix",
            type: "text",
            label: "Postal Prefix",
            placeHolder: "380",
            required: false,
            prevFocusField: "cityName",
            nextFocusField: "latitude",
            className: "col-span-6",
            maxLength: 6,
        },
        {
            id: "latitude",
            type: "number",
            label: "Latitude",
            placeHolder: "23.0225",
            required: false,
            prevFocusField: "postalPrefix",
            nextFocusField: "longitude",
            className: "col-span-6",
        },
        {
            id: "longitude",
            type: "number",
            label: "Longitude",
            placeHolder: "72.5714",
            required: false,
            prevFocusField: "latitude",
            nextFocusField: "isActive",
            className: "col-span-6",
        },
    ];

    const initialValue = {
        countryId: "",
        stateId: "",
        cityCode: "",
        cityName: "",
        postalPrefix: "",
        latitude: "",
        longitude: "",
        isActive: true,
    };

    const cityRowData = [
        {
            cityId: 1,
            countryId: 1,
            countryName: "India",
            stateId: 1,
            stateName: "Gujarat",
            cityCode: "AMD",
            cityName: "Ahmedabad",
            postalPrefix: "380",
            latitude: 23.0225,
            longitude: 72.5714,
            isActive: true,
        },
        {
            cityId: 2,
            countryId: 1,
            countryName: "India",
            stateId: 1,
            stateName: "Gujarat",
            cityCode: "ST",
            cityName: "Surat",
            postalPrefix: "395",
            latitude: 21.1702,
            longitude: 72.8311,
            isActive: true,
        },
        {
            cityId: 3,
            countryId: 1,
            countryName: "India",
            stateId: 2,
            stateName: "Maharashtra",
            cityCode: "MUM",
            cityName: "Mumbai",
            postalPrefix: "400",
            latitude: 19.0760,
            longitude: 72.8777,
            isActive: true,
        },
        {
            cityId: 4,
            countryId: 1,
            countryName: "India",
            stateId: 2,
            stateName: "Maharashtra",
            cityCode: "PUN",
            cityName: "Pune",
            postalPrefix: "411",
            latitude: 18.5204,
            longitude: 73.8567,
            isActive: true,
        },
        {
            cityId: 5,
            countryId: 1,
            countryName: "India",
            stateId: 3,
            stateName: "Rajasthan",
            cityCode: "JPR",
            cityName: "Jaipur",
            postalPrefix: "302",
            latitude: 26.9124,
            longitude: 75.7873,
            isActive: true,
        },
        {
            cityId: 6,
            countryId: 2,
            countryName: "United States",
            stateId: 4,
            stateName: "California",
            cityCode: "LA",
            cityName: "Los Angeles",
            postalPrefix: "900",
            latitude: 34.0522,
            longitude: -118.2437,
            isActive: true,
        },
        {
            cityId: 7,
            countryId: 2,
            countryName: "United States",
            stateId: 5,
            stateName: "Texas",
            cityCode: "HOU",
            cityName: "Houston",
            postalPrefix: "770",
            latitude: 29.7604,
            longitude: -95.3698,
            isActive: true,
        },
        {
            cityId: 8,
            countryId: 3,
            countryName: "Canada",
            stateId: 6,
            stateName: "Ontario",
            cityCode: "TOR",
            cityName: "Toronto",
            postalPrefix: "M5",
            latitude: 43.6532,
            longitude: -79.3832,
            isActive: true,
        },
    ];

    return {
        cityListingColDef,
        citySchema,
        cityRowData,
        initialValue,
    };
};

export default useCityMasterConfig;