import React from "react";

const useStateMasterConfig = () => {
    const stateListingColDef = [
        {
            id: "stateId",
            field: "stateId",
            headerName: "Id",
            width: 80,
        },
        {
            id: "countryName",
            field: "countryName",
            headerName: "Country",
            width: 180,
        },
        {
            id: "stateCode",
            field: "stateCode",
            headerName: "State Code",
            width: 130,
        },
        {
            id: "stateName",
            field: "stateName",
            headerName: "State Name",
            width: 220,
        },
        {
            id: "gstStateCode",
            field: "gstStateCode",
            headerName: "GST State Code",
            width: 150,
        },
        {
            id: "capital",
            field: "capital",
            headerName: "Capital",
            width: 180,
        },
    ];

    const stateSchema = [
        {
            id: "countryId",
            type: "selectWrapper",
            label: "Country",
            placeHolder: "Select Country",
            required: true,
            nextFocusField: "stateCode",
            className: "col-span-6",
            options: [
                { label: "India", value: 1 },
                { label: "United States", value: 2 },
                { label: "United Kingdom", value: 3 },
                { label: "Canada", value: 4 },
            ],
        },
        {
            id: "stateCode",
            type: "text",
            label: "State Code",
            placeHolder: "GJ",
            required: true,
            prevFocusField: "countryId",
            nextFocusField: "stateName",
            className: "col-span-6",
            maxLength: 3,
            textTransform: "uppercase",
        },
        {
            id: "stateName",
            type: "text",
            label: "State Name",
            placeHolder: "Enter State Name",
            required: true,
            prevFocusField: "stateCode",
            nextFocusField: "gstStateCode",
            className: "col-span-6",
        },
        {
            id: "gstStateCode",
            type: "number",
            label: "GST State Code",
            placeHolder: "24",
            required: true,
            prevFocusField: "stateName",
            nextFocusField: "capital",
            className: "col-span-6",
        },
        {
            id: "capital",
            type: "text",
            label: "Capital",
            placeHolder: "Enter Capital",
            required: false,
            prevFocusField: "gstStateCode",
            nextFocusField: "isActive",
            className: "col-span-6",
        },
    ];

    const stateRowData = [
        {
            stateId: 1,
            countryId: 1,
            countryName: "India",
            stateCode: "GJ",
            stateName: "Gujarat",
            gstStateCode: "24",
            capital: "Gandhinagar",
            isActive: true,
        },
        {
            stateId: 2,
            countryId: 1,
            countryName: "India",
            stateCode: "MH",
            stateName: "Maharashtra",
            gstStateCode: "27",
            capital: "Mumbai",
            isActive: true,
        },
        {
            stateId: 3,
            countryId: 1,
            countryName: "India",
            stateCode: "RJ",
            stateName: "Rajasthan",
            gstStateCode: "08",
            capital: "Jaipur",
            isActive: true,
        },
        {
            stateId: 4,
            countryId: 1,
            countryName: "India",
            stateCode: "DL",
            stateName: "Delhi",
            gstStateCode: "07",
            capital: "New Delhi",
            isActive: true,
        },
        {
            stateId: 5,
            countryId: 1,
            countryName: "India",
            stateCode: "KA",
            stateName: "Karnataka",
            gstStateCode: "29",
            capital: "Bengaluru",
            isActive: true,
        },
        {
            stateId: 6,
            countryId: 2,
            countryName: "United States",
            stateCode: "CA",
            stateName: "California",
            gstStateCode: "-",
            capital: "Sacramento",
            isActive: true,
        },
        {
            stateId: 7,
            countryId: 2,
            countryName: "United States",
            stateCode: "TX",
            stateName: "Texas",
            gstStateCode: "-",
            capital: "Austin",
            isActive: true,
        },
        {
            stateId: 8,
            countryId: 3,
            countryName: "United Kingdom",
            stateCode: "ENG",
            stateName: "England",
            gstStateCode: "-",
            capital: "London",
            isActive: true,
        },
        {
            stateId: 9,
            countryId: 4,
            countryName: "Canada",
            stateCode: "ON",
            stateName: "Ontario",
            gstStateCode: "-",
            capital: "Toronto",
            isActive: true,
        },
        {
            stateId: 10,
            countryId: 1,
            countryName: "India",
            stateCode: "TN",
            stateName: "Tamil Nadu",
            gstStateCode: "33",
            capital: "Chennai",
            isActive: false,
        },
    ];

    return {
        stateListingColDef,
        stateSchema,
        stateRowData,
    };
};

export default useStateMasterConfig;