import { api, apiEndpoints } from "@/api/api";

const useDesignationConfig = ({ handleDelete, EmployeeData } = {}) => {
    const DesignationListingColDef = [
        {
            id: "designationname",
            field: "designationname",
            headerName: "Designation Name",
            width: 160,
        },
        {
            id: "designationcode",
            field: "designationcode",
            headerName: "Designation Code",
            width: 150,
        },

        {
            id: "shortname",
            field: "shortname",
            headerName: "Short Name",
            width: 120,
        },

        {
            id: "companyName",
            field: "companyName",
            headerName: "Company",
            width: 180,
        },

        {
            id: "branchname",
            field: "branchname",
            headerName: "Branch",
            width: 180,
        },

        {
            id: "departmentname",
            field: "departmentname",
            headerName: "Department",
            width: 160,
        },

        {
            id: "employeeCount",
            field: "employeeCount",
            headerName: "Employees",
            width: 120,
        },
        {
            id: "probationPeriod",
            field: "probationPeriod",
            headerName: "Probation Period",
            width: 140,
        },
        {
            id: "noticePeriod",
            field: "noticePeriod",
            headerName: "Notice Period",
            width: 120,
        },
        {
            id: "departmentHeadId",
            field: "departmentHeadId",
            headerName: "department Head",
            width: 140,
        },
        {
            id: "mentorId",
            field: "mentorId",
            headerName: "Mentor",
            width: 140,
        },
        {
            id: "salaryGrade",
            field: "salaryGrade",
            headerName: "salary Grade",
            width: 120,
        },
        {
            id: "attendancePolicy",
            field: "attendancePolicy",
            headerName: "Attendance Policy",
            width: 140,
        },
        {
            id: "officialEmail",
            field: "officialEmail",
            headerName: "Official Email",
            width: 200,
        },
        {
            id: "officialPhone",
            field: "officialPhone",
            headerName: "Official Phone",
            width: 120,
        },
        {
            id: "workMode",
            field: "workMode",
            headerName: "Work Mode",
            width: 120,
        },
        {
            id: "payrollGroup",
            field: "payrollGroup",
            headerName: "Payroll Group",
            width: 100,
        },
        {
            type: "status",
            id: "overtimeEligible",
            field: "overtimeEligible",
            headerName: "Overtime",
            width: 100,
        },
        {
            type: "status",
            id: "bonusEligible",
            field: "bonusEligible",
            headerName: "Bonus",
            width: 80,
        },
        {
            type: "status",
            id: "pfApplicable",
            field: "pfApplicable",
            headerName: "PF",
            width: 80,
        },
        {
            type: "status",
            id: "esiApplicable",
            field: "esiApplicable",
            headerName: "ESI",
            width: 80,
        },
        {
            type: "status",
            id: "professionalTaxApplicable",
            field: "professionalTaxApplicable",
            headerName: "Pro. Tax",
            width: 80,
        },
        {
            id: "action",
            field: "action",
            headerName: "Action",
            width: 80,
            type: "actions",

            onClick: (data) => {
                handleDelete(data._id);
            },
        },
    ];

    const basicInfoSchema = [
        {
            id: "designationname",
            type: "text",
            label: "Designation Name",
            placeHolder: "e.g. Acme Corporation",
            required: true,
            nextFocusField: "designationcode",
            prevFocusField: 'designationname',
            className: "col-span-3",
        },
        {
            id: "designationcode",
            type: "text",
            label: "Designation Code",
            placeHolder: "e.g. Acme Corp LLC",
            required: true,
            prevFocusField: "companyName",
            nextFocusField: "shortname",
            className: "col-span-3",
        },
        {
            id: "shortname",
            type: "text",
            label: "Short Name",
            placeHolder: "e.g. Acme Corp LLC",
            required: true,
            prevFocusField: "designationcode",
            nextFocusField: "company",
            className: "col-span-3",
        },
    ];

    const jobAssignmentSchema = [
        {
            id: "company",
            type: "selectWrapper",
            label: "Company",
            placeHolder: "Select Company",
            required: true,
            api: api + apiEndpoints.organization.company.CompanyHelp,
            labelKey: "companyName",
            valueKey: "_id",
            className: "col-span-4",
            prevFocusField: "shortname",
            nextFocusField: "branch",
        },
        {
            id: "branch",
            type: "selectWrapper",
            label: "Branch",
            placeHolder: "Select Branch",
            required: true,
            api: api + apiEndpoints.organization.branch.BranchHelp,
            labelKey: "branchname",
            valueKey: "_id",
            className: "col-span-4",
            prevFocusField: "company",
            nextFocusField: "department",
        },
        {
            id: "department",
            type: "selectWrapper",
            label: "Department",
            api: api + apiEndpoints.organization.department.DepartmentHelp,
            labelKey: "departmentname",
            valueKey: "_id",
            placeHolder: "Select Department",
            required: true,
            className: "col-span-4",
            prevFocusField: "branch",
            nextFocusField: "designationId",
        },
        {
            id: "designationId",
            type: "selectWrapper",
            label: "Designation",
            placeHolder: "Select Designation",
            // required: true,
            api: api + apiEndpoints.organization.designation.DesignationHelp,
            labelKey: "desigantioname",
            valueKey: "_id",
            className: "col-span-4",
            prevFocusField: "department",
            nextFocusField: "businessUnitId",
        },
        {
            id: "businessUnitId",
            type: "selectWrapper",
            label: "Business Unit",
            placeHolder: "Select Business Unit",
            className: "col-span-4",
            prevFocusField: "designationId",
            nextFocusField: "employmentType",
            options: [
                { label: "Information Technology", value: "IT" },
                { label: "Human Resources", value: "HR" },
                { label: "Finance & Accounting", value: "FINANCE" },
                { label: "Sales & Marketing", value: "SALES_MARKETING" },
                { label: "Operations", value: "OPERATIONS" },
                { label: "Research & Development", value: "R_AND_D" },
                { label: "Customer Support", value: "CUSTOMER_SUPPORT" },
                { label: "Administration", value: "ADMIN" },
            ],
        },

    ];
    const employmentSchema = [
        {
            id: "employmentType",
            type: "selectWrapper",
            label: "Employment Type",
            placeHolder: "Select Employment Type",
            required: true,
            className: "col-span-4",
            prevFocusField: "businessUnitId",
            nextFocusField: "employmentStatus",
            options: [
                { label: "Full Time", value: "FULL_TIME" },
                { label: "Part Time", value: "PART_TIME" },
                { label: "Contract", value: "CONTRACT" },
                { label: "Temporary", value: "TEMPORARY" },
                { label: "Intern", value: "INTERN" },
                { label: "Trainee", value: "TRAINEE" },
                { label: "Freelancer", value: "FREELANCER" },
            ],
        },
        {
            id: "employmentStatus",
            type: "selectWrapper",
            label: "Employment Status",
            placeHolder: "Select Status",
            required: true,
            className: "col-span-4",
            prevFocusField: "employmentType",
            nextFocusField: "joiningDate",
            options: [
                { label: "Active", value: "ACTIVE" },
                { label: "Probation", value: "PROBATION" },
                { label: "On Leave", value: "ON_LEAVE" },
                { label: "Suspended", value: "SUSPENDED" },
                { label: "Resigned", value: "RESIGNED" },
                { label: "Terminated", value: "TERMINATED" },
                { label: "Retired", value: "RETIRED" },
                { label: "Inactive", value: "INACTIVE" },
            ],
        },
        {
            id: "joiningDate",
            type: "date",
            label: "Date of Joining",
            required: true,
            className: "col-span-4",
            prevFocusField: "employmentStatus",
            nextFocusField: "confirmationDate",
        },
        {
            id: "confirmationDate",
            type: "date",
            label: "Confirmation Date",
            className: "col-span-4",
            prevFocusField: "joiningDate",
            nextFocusField: "probationPeriod",
        },
        {
            id: "probationPeriod",
            type: "selectWrapper",
            label: "Probation Period",
            className: "col-span-4",
            prevFocusField: "confirmationDate",
            nextFocusField: "noticePeriod",
            options: [
                { label: "No Probation", value: "0" },
                { label: "1 Month", value: "1_MONTH" },
                { label: "2 Months", value: "2_MONTHS" },
                { label: "3 Months", value: "3_MONTHS" },
                { label: "4 Months", value: "4_MONTHS" },
                { label: "6 Months", value: "6_MONTHS" },
                { label: "12 Months", value: "12_MONTHS" },
            ],
        },
        {
            id: "noticePeriod",
            type: "selectWrapper",
            label: "Notice Period",
            className: "col-span-4",
            prevFocusField: "probationPeriod",
            nextFocusField: "workingShifts",
            options: [
                { label: "No Notice Period", value: "0" },
                { label: "7 Days", value: "7_DAYS" },
                { label: "15 Days", value: "15_DAYS" },
                { label: "30 Days", value: "30_DAYS" },
                { label: "45 Days", value: "45_DAYS" },
                { label: "60 Days", value: "60_DAYS" },
                { label: "90 Days", value: "90_DAYS" },
            ],
        },
    ];
    const workSchema = [
        {
            id: "workingShift",
            type: "selectWrapper",
            label: "Working Shift",
            className: "col-span-4",
            prevFocusField: "noticePeriod",
            nextFocusField: "holidayCalendar",
            options: [
                { label: "General Shift", value: "GENERAL" },
                { label: "Morning Shift", value: "MORNING" },
                { label: "Afternoon Shift", value: "AFTERNOON" },
                { label: "Evening Shift", value: "EVENING" },
                { label: "Night Shift", value: "NIGHT" },
                { label: "Rotational Shift", value: "ROTATIONAL" },
                { label: "Flexible Shift", value: "FLEXIBLE" },
            ]
        },
        {
            id: "holidayCalendar",
            type: "selectWrapper",
            label: "Holiday Calendar",
            className: "col-span-4",
            isMultiSelect: true,
            api: api + apiEndpoints.master.holiday.HolidayHelp,
            labelKey: "holidayName",
            valueKey: "_id",
            prevFocusField: "workingShift",
            nextFocusField: "weeklyOff",

        },
        {
            id: "weeklyOff",
            type: "selectWrapper",
            label: "Weekly Off",
            isMultiSelect: true,
            className: "col-span-4",
            prevFocusField: "holidayCalendar",
            nextFocusField: "attendancePolicy",
            options: [
                { label: "Sunday", value: "SUNDAY" },
                { label: "Monday", value: "MONDAY" },
                { label: "Tuesday", value: "TUESDAY" },
                { label: "Wednesday", value: "WEDNESDAY" },
                { label: "Thursday", value: "THURSDAY" },
                { label: "Friday", value: "FRIDAY" },
                { label: "Saturday", value: "SATURDAY" },
            ]
        },
        {
            id: "attendancePolicy",
            type: "selectWrapper",
            label: "Attendance Policy",
            className: "col-span-4",
            prevFocusField: "weeklyOff",
            nextFocusField: "officialEmail",
            options: [
                { label: "Standard Attendance Policy", value: "STANDARD" },
                { label: "Flexible Attendance Policy", value: "FLEXIBLE" },
                { label: "Shift Based Attendance Policy", value: "SHIFT_BASED" },
                { label: "Biometric Attendance Policy", value: "BIOMETRIC" },
                { label: "Remote / Work From Home Policy", value: "REMOTE" },
                { label: "Contract Employee Policy", value: "CONTRACT" },
            ]
        },
        {
            id: "officialEmail",
            type: "email",
            label: "Official Email",
            placeHolder: "Enter Official Email",
            className: "col-span-4",
            nextFocusField: "officialPhone",
            prevFocusField: "attendancePolicy",
            nextFocusField: "officialPhone",
        },
        {
            id: "officialPhone",
            type: "phone",
            label: "Official Phone",
            className: "col-span-4",
            prevFocusField: "officialEmail",
            nextFocusField: "extensionNumber",
        },
        {
            id: "extensionNumber",
            type: "number",
            label: "Extension Number",
            className: "col-span-4",
            prevFocusField: "officialPhone",
            nextFocusField: "workMode",
        },
        {
            id: "workMode",
            type: "selectWrapper",
            label: "Work Mode",
            className: "col-span-4",
            prevFocusField: "extensionNumber",
            nextFocusField: "reportingManagerId",
            options: [
                { label: "On-Site", value: "ON_SITE" },
                { label: "Work From Home", value: "WORK_FROM_HOME" },
                { label: "Hybrid", value: "HYBRID" },
                { label: "Remote", value: "REMOTE" },
                { label: "Field Work", value: "FIELD_WORK" },
            ]
        },
    ];
    const reportingStructreSchema = [
        {
            id: "reportingManagerId",
            type: "selectWrapper",
            label: "Reporting Manager",
            // required: true,
            className: "col-span-6",
            options: EmployeeData,
            prevFocusField: "workMode",
            nextFocusField: "skipLevelManagerId",
        },
        {
            id: "skipLevelManagerId",
            type: "selectWrapper",
            label: "Skip Level Manager",
            className: "col-span-6",
            options: EmployeeData,
            prevFocusField: "reportingManagerId",
            nextFocusField: "departmentHeadId",
        },
        {
            id: "departmentHeadId",
            type: "selectWrapper",
            label: "Department Head",
            className: "col-span-6",
            options: EmployeeData,
            prevFocusField: "skipLevelManagerId",
            nextFocusField: "mentorId",
        },
        {
            id: "mentorId",
            type: "selectWrapper",
            label: "Mentor",
            className: "col-span-6",
            options: EmployeeData,
            prevFocusField: "departmentHeadId",
            nextFocusField: "jobGrade",
        },
    ];
    const gradeSchema = [
        {
            id: "jobGrade",
            type: "selectWrapper",
            label: "Job Grade",
            className: "col-span-6",
            prevFocusField: "mentorId",
            nextFocusField: "jobLevel",
            options: [
                { label: "Entry Level", value: "ENTRY" },
                { label: "Junior", value: "JUNIOR" },
                { label: "Intermediate", value: "INTERMEDIATE" },
                { label: "Senior", value: "SENIOR" },
                { label: "Lead", value: "LEAD" },
                { label: "Assistant Manager", value: "ASSISTANT_MANAGER" },
                { label: "Manager", value: "MANAGER" },
                { label: "Senior Manager", value: "SENIOR_MANAGER" },
                { label: "Head", value: "HEAD" },
                { label: "Director", value: "DIRECTOR" },
                { label: "Vice President", value: "VP" },
                { label: "C-Level", value: "C_LEVEL" },
            ]
        },
        {
            id: "jobLevel",
            type: "selectWrapper",
            label: "Job Level",
            className: "col-span-6",
            prevFocusField: "jobGrade",
            nextFocusField: "band",
            options: [
                { label: "Entry Level", value: "ENTRY" },
                { label: "Junior", value: "JUNIOR" },
                { label: "Intermediate", value: "INTERMEDIATE" },
                { label: "Senior", value: "SENIOR" },
                { label: "Lead", value: "LEAD" },
                { label: "Assistant Manager", value: "ASSISTANT_MANAGER" },
                { label: "Manager", value: "MANAGER" },
                { label: "Senior Manager", value: "SENIOR_MANAGER" },
                { label: "Head", value: "HEAD" },
                { label: "Director", value: "DIRECTOR" },
                { label: "Vice President", value: "VP" },
                { label: "C-Level", value: "C_LEVEL" },
            ],
        },
        {
            id: "band",
            type: "selectWrapper",
            label: "Band",
            className: "col-span-6",
            prevFocusField: "jobLevel",
            nextFocusField: "salaryGrade",
            options: [
                { label: "Band A", value: "A" },
                { label: "Band B", value: "B" },
                { label: "Band C", value: "C" },
                { label: "Band D", value: "D" },
                { label: "Band E", value: "E" },
                { label: "Band F", value: "F" },
                { label: "Band G", value: "G" },
            ],
        },
        {
            id: "salaryGrade",
            type: "selectWrapper",
            label: "Salary Grade",
            className: "col-span-6",
            prevFocusField: "band",
            nextFocusField: "payrollGroup",
            options: [
                { label: "SG-01", value: "SG01" },
                { label: "SG-02", value: "SG02" },
                { label: "SG-03", value: "SG03" },
                { label: "SG-04", value: "SG04" },
                { label: "SG-05", value: "SG05" },
                { label: "SG-06", value: "SG06" },
                { label: "SG-07", value: "SG07" },
                { label: "SG-08", value: "SG08" },
                { label: "SG-09", value: "SG09" },
                { label: "SG-10", value: "SG10" },
            ],
        },
    ];

    const payrollSchema = [
        {
            id: "payrollGroup",
            type: "selectWrapper",
            label: "Payroll Group",
            className: "col-span-6",
            prevFocusField: "salaryGrade",
            nextFocusField: "defaultRole",
            options: [
                { label: "Monthly Payroll", value: "MONTHLY" },
                { label: "Weekly Payroll", value: "WEEKLY" },
                { label: "Bi-Weekly Payroll", value: "BI_WEEKLY" },
                { label: "Contract Payroll", value: "CONTRACT" },
            ],
        },
        {
            id: "defaultRole",
            type: "selectWrapper",
            label: "Default Role",
            className: "col-span-6",
            prevFocusField: "payrollGroup",
            nextFocusField: "accessLevel",
            options: [
                { label: "Employee", value: "EMPLOYEE" },
                { label: "Manager", value: "MANAGER" },
                { label: "HR Manager", value: "HR_MANAGER" },
                { label: "HR Executive", value: "HR_EXECUTIVE" },
                { label: "Payroll Administrator", value: "PAYROLL_ADMIN" },
                { label: "System Administrator", value: "SYSTEM_ADMIN" },
            ],
        },
        {
            id: "accessLevel",
            type: "selectWrapper",
            label: "Access Level",
            className: "col-span-6",
            prevFocusField: "defaultRole",
            nextFocusField: "userAccount",
            options: [
                { label: "Basic", value: "BASIC" },
                { label: "Standard", value: "STANDARD" },
                { label: "Manager", value: "MANAGER" },
                { label: "HR", value: "HR" },
                { label: "Administrator", value: "ADMIN" },
                { label: "Super Administrator", value: "SUPER_ADMIN" },
            ],
        },
        {
            id: "userAccount",
            type: "selectWrapper",
            label: "User Account",
            className: "col-span-6",
            prevFocusField: "accessLevel",
            nextFocusField: "userAccount",
            options: [
                { label: "Create New Account", value: "CREATE" },
                { label: "Link Existing Account", value: "LINK_EXISTING" },
                { label: "No User Account", value: "NONE" },
            ],
        },
    ];
    const payrollToggleConfig = [
        {
            id: "overtimeEligible",
            title: "Overtime Eligible",
            defaultValue: false,
        },
        {
            id: "bonusEligible",
            title: "Bonus Eligible",
            defaultValue: false,
        },
        {
            id: "pfApplicable",
            title: "PF Applicable",
            defaultValue: false,
        },
        {
            id: "esiApplicable",
            title: "ESI Applicable",
            defaultValue: false,
        },
        {
            id: "professionalTaxApplicable",
            title: "Professional Tax",
            defaultValue: false,
        },
    ];

    return {
        basicInfoSchema, DesignationListingColDef, jobAssignmentSchema,
        reportingStructreSchema,
        gradeSchema,
        employmentSchema,
        workSchema,
        payrollSchema,
        payrollToggleConfig
    }
}

export default useDesignationConfig