import React from 'react'

const useCountyMasterConfig = () => {
    const countryListingListingColDef = [
        {
            id: "countryId",
            field: "countryId",
            headerName: "Id",
            width: 80,
        },
        {
            id: "countryName",
            field: "countryName",
            headerName: "Country Name",
            width: 220,
        },
        {
            id: "countryCode",
            field: "countryCode",
            headerName: "Country Code",
            width: 130,
        },
        {
            id: "isoCode",
            field: "isoCode",
            headerName: "ISO Code",
            width: 120,
        },
        {
            id: "phoneCode",
            field: "phoneCode",
            headerName: "Phone Code",
            width: 120,
        },
        {
            id: "nationality",
            field: "nationality",
            headerName: "Nationality",
            width: 180,
        },
    ];

    const countrySchema = [
        {
            id: "countryName",
            type: "text",
            label: "Country Name",
            placeHolder: "Enter country name",
            required: true,
            nextFocusField: "countryCode",
            className: "col-span-6",
        },
        {
            id: "countryCode",
            type: "text",
            label: "Country Code",
            placeHolder: "IN",
            required: true,
            prevFocusField: "countryName",
            nextFocusField: "isoCode",
            className: "col-span-6",
            maxLength: 2,
            textTransform: "uppercase",
        },
        {
            id: "isoCode",
            type: "text",
            label: "ISO Code",
            placeHolder: "IND",
            required: true,
            prevFocusField: "countryCode",
            nextFocusField: "phoneCode",
            className: "col-span-6",
            maxLength: 3,
            textTransform: "uppercase",
        },
        {
            id: "phoneCode",
            type: "text",
            label: "Phone Code",
            placeHolder: "+91",
            required: false,
            prevFocusField: "isoCode",
            nextFocusField: "nationality",
            className: "col-span-6",
        },
        {
            id: "nationality",
            type: "text",
            label: "Nationality",
            placeHolder: "Indian",
            required: false,
            prevFocusField: "phoneCode",
            nextFocusField: "isActive",
            className: "col-span-6",
        },
    ];

    const countryRowData = [
        {
            countryId: 1,
            countryName: "India",
            countryCode: "IN",
            isoCode: "IND",
            phoneCode: "+91",
            nationality: "Indian",
            isActive: true,
        },
        {
            countryId: 2,
            countryName: "United States",
            countryCode: "US",
            isoCode: "USA",
            phoneCode: "+1",
            nationality: "American",
            isActive: true,
        },
        {
            countryId: 3,
            countryName: "United Kingdom",
            countryCode: "GB",
            isoCode: "GBR",
            phoneCode: "+44",
            nationality: "British",
            isActive: true,
        },
        {
            countryId: 4,
            countryName: "Canada",
            countryCode: "CA",
            isoCode: "CAN",
            phoneCode: "+1",
            nationality: "Canadian",
            isActive: true,
        },
        {
            countryId: 5,
            countryName: "Australia",
            countryCode: "AU",
            isoCode: "AUS",
            phoneCode: "+61",
            nationality: "Australian",
            isActive: true,
        },
        {
            countryId: 6,
            countryName: "Germany",
            countryCode: "DE",
            isoCode: "DEU",
            phoneCode: "+49",
            nationality: "German",
            isActive: true,
        },
        {
            countryId: 7,
            countryName: "France",
            countryCode: "FR",
            isoCode: "FRA",
            phoneCode: "+33",
            nationality: "French",
            isActive: true,
        },
        {
            countryId: 8,
            countryName: "Japan",
            countryCode: "JP",
            isoCode: "JPN",
            phoneCode: "+81",
            nationality: "Japanese",
            isActive: true,
        },
        {
            countryId: 9,
            countryName: "Singapore",
            countryCode: "SG",
            isoCode: "SGP",
            phoneCode: "+65",
            nationality: "Singaporean",
            isActive: true,
        },
        {
            countryId: 10,
            countryName: "United Arab Emirates",
            countryCode: "AE",
            isoCode: "ARE",
            phoneCode: "+971",
            nationality: "Emirati",
            isActive: false,
        },
    ];
    return { countryListingListingColDef, countrySchema, countryRowData };
}

export default useCountyMasterConfig