import React from "react";

const useEmployeeConfig = () => {
    const employeeListingColDef = [];

    const personalInformationSchema = [
        {
            id: "employeeId",
            type: "text",
            label: "Employee ID",
            placeHolder: "Auto Generated",
            required: true,
            disabled: true,
            nextFocusField: "firstName",
            className: "col-span-6",
        },
        {
            id: "firstName",
            type: "text",
            label: "First Name",
            placeHolder: "Enter First Name",
            required: true,
            prevFocusField: "employeeId",
            nextFocusField: "middleName",
            className: "col-span-6",
        },
        {
            id: "middleName",
            type: "text",
            label: "Middle Name",
            placeHolder: "Enter Middle Name",
            required: false,
            prevFocusField: "firstName",
            nextFocusField: "lastName",
            className: "col-span-6",
        },
        {
            id: "lastName",
            type: "text",
            label: "Last Name",
            placeHolder: "Enter Last Name",
            required: true,
            prevFocusField: "middleName",
            nextFocusField: "gender",
            className: "col-span-6",
        },
        {
            id: "gender",
            type: "selectWrapper",
            label: "Gender",
            placeHolder: "Select Gender",
            required: true,
            prevFocusField: "lastName",
            nextFocusField: "dateOfBirth",
            className: "col-span-6",
            options: [
                {
                    label: "Male",
                    value: "male",
                },
                {
                    label: "Female",
                    value: "female",
                },
                {
                    label: "Other",
                    value: "other",
                },
            ],
        },
        {
            id: "dateOfBirth",
            type: "date",
            label: "Date of Birth",
            placeHolder: "Select Date of Birth",
            required: true,
            prevFocusField: "gender",
            nextFocusField: "maritalStatus",
            className: "col-span-6",
        },
        {
            id: "maritalStatus",
            type: "selectWrapper",
            label: "Marital Status",
            placeHolder: "Select Marital Status",
            required: false,
            prevFocusField: "dateOfBirth",
            nextFocusField: "bloodGroup",
            className: "col-span-6",
            options: [
                {
                    label: "Single",
                    value: "single",
                },
                {
                    label: "Married",
                    value: "married",
                },
                {
                    label: "Divorced",
                    value: "divorced",
                },
                {
                    label: "Widowed",
                    value: "widowed",
                },
            ],
        },
        {
            id: "bloodGroup",
            type: "selectWrapper",
            label: "Blood Group",
            placeHolder: "Select Blood Group",
            required: false,
            prevFocusField: "maritalStatus",
            nextFocusField: "",
            className: "col-span-6",
            options: [
                { label: "A+", value: "A+" },
                { label: "A-", value: "A-" },
                { label: "B+", value: "B+" },
                { label: "B-", value: "B-" },
                { label: "AB+", value: "AB+" },
                { label: "AB-", value: "AB-" },
                { label: "O+", value: "O+" },
                { label: "O-", value: "O-" },
            ],
        },
    ];

    const organizationInformationSchema = [
        {
            id: "companyId",
            type: "selectWrapper",
            label: "Company",
            placeHolder: "Select Company",
            required: true,
            nextFocusField: "branchId",
            className: "col-span-6",
            options: [
                { label: "Elite Enterprises Inc.", value: 1 },
                { label: "Orvexa Technologies", value: 2 },
            ],
        },
        {
            id: "branchId",
            type: "selectWrapper",
            label: "Branch",
            placeHolder: "Select Branch",
            required: true,
            prevFocusField: "companyId",
            nextFocusField: "departmentId",
            className: "col-span-6",
            options: [
                { label: "Main Headquarters", value: 1 },
                { label: "Ahmedabad Branch", value: 2 },
            ],
        },
        {
            id: "departmentId",
            type: "selectWrapper",
            label: "Department",
            placeHolder: "Select Department",
            required: true,
            prevFocusField: "branchId",
            nextFocusField: "designationId",
            className: "col-span-6",
            options: [
                { label: "Engineering", value: 1 },
                { label: "HR", value: 2 },
                { label: "Accounts", value: 3 },
            ],
        },
        {
            id: "designationId",
            type: "selectWrapper",
            label: "Designation",
            placeHolder: "Select Designation",
            required: true,
            prevFocusField: "departmentId",
            nextFocusField: "reportingManager",
            className: "col-span-6",
            options: [
                { label: "Software Engineer", value: 1 },
                { label: "Senior Developer", value: 2 },
                { label: "Team Lead", value: 3 },
            ],
        },
        {
            id: "reportingManager",
            type: "selectWrapper",
            label: "Reporting Manager",
            placeHolder: "Select Manager",
            required: false,
            prevFocusField: "designationId",
            nextFocusField: "employmentType",
            className: "col-span-6",
            options: [
                { label: "John Smith", value: 1 },
                { label: "David Wilson", value: 2 },
            ],
        },
        {
            id: "employmentType",
            type: "selectWrapper",
            label: "Employment Type",
            placeHolder: "Select Employment Type",
            required: true,
            prevFocusField: "reportingManager",
            nextFocusField: "employeeStatus",
            className: "col-span-6",
            options: [
                { label: "Full Time", value: "FULL_TIME" },
                { label: "Part Time", value: "PART_TIME" },
                { label: "Contract", value: "CONTRACT" },
                { label: "Intern", value: "INTERN" },
            ],
        },
        {
            id: "employeeStatus",
            type: "selectWrapper",
            label: "Employee Status",
            placeHolder: "Select Status",
            required: true,
            prevFocusField: "employmentType",
            nextFocusField: "joiningDate",
            className: "col-span-6",
            options: [
                { label: "Active", value: "ACTIVE" },
                { label: "Inactive", value: "INACTIVE" },
                { label: "Notice Period", value: "NOTICE" },
            ],
        },
        {
            id: "joiningDate",
            type: "date",
            label: "Joining Date",
            required: true,
            prevFocusField: "employeeStatus",
            nextFocusField: "confirmationDate",
            className: "col-span-6",
        },
        {
            id: "confirmationDate",
            type: "date",
            label: "Confirmation Date",
            required: false,
            prevFocusField: "joiningDate",
            nextFocusField: "probationPeriod",
            className: "col-span-6",
        },
        {
            id: "probationPeriod",
            type: "number",
            label: "Probation Period",
            placeHolder: "6",
            required: false,
            suffix: "Months",
            prevFocusField: "confirmationDate",
            className: "col-span-6",
        },
    ];

    const contactInformationSchema = [
        {
            id: "officialEmail",
            type: "text",
            label: "Official Email",
            placeHolder: "e.g. john.doe@company.com",
            required: true,
            nextFocusField: "personalEmail",
            className: "col-span-6",
        },
        {
            id: "personalEmail",
            type: "number",
            label: "Personal Email",
            placeHolder: "e.g. john@gmail.com",
            required: true,
            prevFocusField: "officialEmail",
            nextFocusField: "mobileNumber",
            className: "col-span-6",
        },
        {
            id: "mobileNumber",
            type: "number",
            label: "Mobile Number",
            placeHolder: "Enter Mobile Number",
            required: true,
            prevFocusField: "personalEmail",
            nextFocusField: "alternateMobile",
            className: "col-span-6",
        },
        {
            id: "alternateMobile",
            type: "number",
            label: "Alternate Mobile",
            placeHolder: "Enter Alternate Mobile",
            required: false,
            prevFocusField: "mobileNumber",
            nextFocusField: "emergencyContactName",
            className: "col-span-6",
        },
        {
            id: "emergencyContactName",
            type: "text",
            label: "Emergency Contact Name",
            placeHolder: "Full Name",
            required: true,
            prevFocusField: "alternateMobile",
            nextFocusField: "emergencyContactNumber",
            className: "col-span-6",
        },
        {
            id: "emergencyContactNumber",
            type: "number",
            label: "Emergency Contact Number",
            placeHolder: "Enter Contact Number",
            required: true,
            prevFocusField: "emergencyContactName",
            nextFocusField: "countryId",
            className: "col-span-6",
        },
        {
            id: "countryId",
            type: "selectWrapper",
            label: "Country",
            placeHolder: "Select Country",
            required: true,
            prevFocusField: "emergencyContactNumber",
            nextFocusField: "stateId",
            className: "col-span-6",
            options: [
                { label: "India", value: 1 },
                { label: "United States", value: 2 },
            ],
        },
        {
            id: "stateId",
            type: "selectWrapper",
            label: "State",
            placeHolder: "Select State",
            required: true,
            prevFocusField: "countryId",
            nextFocusField: "cityId",
            className: "col-span-6",
            options: [
                { label: "Gujarat", value: 1 },
                { label: "Maharashtra", value: 2 },
            ],
        },
        {
            id: "cityId",
            type: "selectWrapper",
            label: "City",
            placeHolder: "Select City",
            required: true,
            prevFocusField: "stateId",
            nextFocusField: "postalCode",
            className: "col-span-6",
            options: [
                { label: "Ahmedabad", value: 1 },
                { label: "Surat", value: 2 },
            ],
        },
        {
            id: "postalCode",
            type: "text",
            label: "Postal Code",
            placeHolder: "380001",
            required: true,
            prevFocusField: "cityId",
            nextFocusField: "currentAddress",
            className: "col-span-6",
            maxLength: 10,
        },
        {
            id: "currentAddress",
            type: "text",
            label: "Current Address",
            placeHolder: "Enter Full Address",
            required: true,
            prevFocusField: "postalCode",
            className: "col-span-12",
            rows: 3,
        },
    ];

    const documentInformationSchema = [
        {
            id: "aadhaarNumber",
            type: "text",
            label: "Aadhaar Number",
            placeHolder: "Enter 12 digit Aadhaar",
            required: true,
            className: "col-span-6",
            maxLength: 12,
            nextFocusField: "panNumber",
        },
        {
            id: "panNumber",
            type: "text",
            label: "PAN Number",
            placeHolder: "Enter PAN",
            required: true,
            className: "col-span-6",
            maxLength: 10,
            textTransform: "uppercase",
            prevFocusField: "aadhaarNumber",
            nextFocusField: "passportNumber",
        },
        {
            id: "passportNumber",
            type: "text",
            label: "Passport Number",
            placeHolder: "Enter Passport Number",
            className: "col-span-6",
            prevFocusField: "panNumber",
            nextFocusField: "drivingLicenseNumber",
        },
        {
            id: "drivingLicenseNumber",
            type: "text",
            label: "Driving License Number",
            placeHolder: "Enter DL Number",
            className: "col-span-6",
            prevFocusField: "passportNumber",
        },
    ];

    const payrollInformationSchema = [
        // Bank Details
        {
            id: "bankName",
            type: "selectWrapper",
            label: "Bank Name",
            placeHolder: "Select Bank",
            required: true,
            className: "col-span-6",
        },
        {
            id: "accountNumber",
            type: "text",
            label: "Account Number",
            placeHolder: "Enter Account Number",
            required: true,
            className: "col-span-6",
        },
        {
            id: "ifscCode",
            type: "text",
            label: "IFSC / SWIFT Code",
            placeHolder: "Enter IFSC",
            required: true,
            className: "col-span-6",
            textTransform: "uppercase",
        },
        {
            id: "uanNumber",
            type: "text",
            label: "UAN Number (PF)",
            placeHolder: "Enter UAN",
            className: "col-span-6",
        },
        {
            id: "pfNumber",
            type: "text",
            label: "PF Number",
            placeHolder: "Enter PF Number",
            className: "col-span-6",
        },
        {
            id: "esiNumber",
            type: "text",
            label: "ESI Number",
            placeHolder: "Enter ESI Number",
            className: "col-span-6",
        },

        // Compensation
        {
            id: "salaryStructure",
            type: "selectWrapper",
            label: "Salary Structure",
            placeHolder: "Select Structure",
            required: true,
            className: "col-span-4",
        },
        {
            id: "ctc",
            type: "number",
            label: "CTC (Annual)",
            placeHolder: "0",
            required: true,
            className: "col-span-4",
        },
        {
            id: "basicSalary",
            type: "number",
            label: "Basic Salary (Monthly)",
            placeHolder: "0",
            required: true,
            className: "col-span-4",
        },
    ];

    const accessInformationSchema = [
        // User Credentials
        {
            id: "username",
            type: "text",
            label: "Username",
            placeHolder: "e.g. john@company.com",
            required: true,
            className: "col-span-10",
            nextFocusField: "password",
        },
        {
            id: "password",
            type: "number",
            label: "Password",
            placeHolder: "Generate Password",
            required: true,
            className: "col-span-4",
            isGeneratePassword: true,
            prevFocusField: "username",
            nextFocusField: "primaryRole",
        },

        // Access Control
        {
            id: "primaryRole",
            type: "selectWrapper",
            label: "Primary Role",
            placeHolder: "Select Role",
            required: true,
            className: "col-span-6",
            options: [
                {
                    label: "Standard Employee",
                    value: "EMPLOYEE",
                },
                {
                    label: "Manager",
                    value: "MANAGER",
                },
                {
                    label: "HR",
                    value: "HR",
                },
                {
                    label: "Administrator",
                    value: "ADMIN",
                },
            ],
        },
        {
            id: "userGroup",
            type: "selectWrapper",
            label: "User Group",
            placeHolder: "Select Group",
            required: true,
            className: "col-span-6",
            options: [
                {
                    label: "Product Development",
                    value: 1,
                },
                {
                    label: "Finance",
                    value: 2,
                },
                {
                    label: "Human Resource",
                    value: 3,
                },
            ],
        },
    ];

    const reviewInformationSchema = [];

    return {
        employeeListingColDef,

        personalInformationSchema,

        organizationInformationSchema,

        contactInformationSchema,

        documentInformationSchema,

        payrollInformationSchema,

        accessInformationSchema,

        reviewInformationSchema,
    };
};

export default useEmployeeConfig;