import { api, apiEndpoints } from "@/api/api";

const useEmployeeConfig = ({ handleDelete } = {}) => {
    const employeeListingColDef = [
        {
            id: "firstName",
            field: "firstName",
            headerName: "Employee Name",
            width: 180,
        },
        {
            id: "lastName",
            field: "lastName",
            headerName: "Surname ",
            width: 140,
        },
        {
            id: "companyName",
            field: "companyName",
            headerName: "Company",
            width: 120,
        },
        {
            id: "branchName",
            field: "branchName",
            headerName: "Branch",
            width: 120,
        },
        {
            id: "departmentname",
            field: "departmentname",
            headerName: "Department",
            width: 180,
        },
        {
            id: "designationName",
            field: "designationName",
            headerName: "Designation",
            width: 180,
        },
        {
            id: "reportingManagerName",
            field: "reportingManagerName",
            headerName: "Manager",
            width: 180,
        },
        {
            id: "employmentType",
            field: "employmentType",
            headerName: "Employment",
            width: 150,
        },
        {
            id: "joiningDate",
            field: "joiningDate",
            headerName: "Joining Date",
            width: 140,
        },
        {
            id: "officialEmail",
            field: "officialEmail",
            headerName: "Official Email",
            width: 240,
        },
        {
            id: "personalEmail",
            field: "personalEmail",
            headerName: "Personal Email Email",
            width: 240,
        },
        {
            id: "mobileNumber",
            field: "mobileNumber",
            headerName: "Mobile",
            width: 150,
        },
        {
            id: "alternateMobile",
            field: "alternateMobile",
            headerName: "Alternate Mobile",
            width: 150,
        },
        {
            id: "emergencyContactNumber",
            field: "emergencyContactNumber",
            headerName: "emergency Contact",
            width: 150,
        },
        {
            id: "confirmationDate",
            field: "confirmationDate",
            headerName: "Confirmation Date",
            width: 150,
        },
        {
            id: "countryName",
            field: "countryName",
            headerName: "Country",
            width: 120,
        },
        {
            id: "stateName",
            field: "stateName",
            headerName: "State",
            width: 120,
        },
        {
            id: "cityName",
            field: "cityName",
            headerName: "City",
            width: 120,
        },
        {
            id: "currentAddress",
            field: "currentAddress",
            headerName: "Address",
            width: 120,
        },

        {
            id: "action",
            field: "action",
            headerName: "Action",
            width: 60,
            type: "actions",
            onClick: (data) => {
                handleDelete(data._id);
            }
        }
    ];

    const personalInformationSchema = [
        {
            id: "employeeId",
            type: "text",
            label: "Employee ID",
            placeHolder: "Auto Generated",
            required: true,
            disabled: true,
            nextFocusField: "firstName",
            className: "col-span-2",
        },
        {
            id: "firstName",
            type: "text",
            label: "First Name",
            placeHolder: "Enter First Name",
            required: true,
            prevFocusField: "employeeId",
            nextFocusField: "middleName",
            className: "col-span-2",
        },
        {
            id: "middleName",
            type: "text",
            label: "Middle Name",
            placeHolder: "Enter Middle Name",
            required: false,
            prevFocusField: "firstName",
            nextFocusField: "lastName",
            className: "col-span-2",
        },
        {
            id: "lastName",
            type: "text",
            label: "Last Name",
            placeHolder: "Enter Last Name",
            required: true,
            prevFocusField: "middleName",
            nextFocusField: "gender",
            className: "col-span-2",
        },
        {
            id: "gender",
            type: "selectWrapper",
            label: "Gender",
            placeHolder: "Select Gender",
            required: true,
            prevFocusField: "lastName",
            nextFocusField: "dateOfBirth",
            className: "col-span-2",
            options: [
                {
                    label: "Male",
                    value: "male",
                },
                {
                    label: "Female",
                    value: "female",
                },
                {
                    label: "Other",
                    value: "other",
                },
            ],
        },
        {
            id: "dateOfBirth",
            type: "date",
            label: "Date of Birth",
            placeHolder: "Select Date of Birth",
            required: true,
            prevFocusField: "gender",
            nextFocusField: "maritalStatus",
            className: "col-span-2",
        },
        {
            id: "maritalStatus",
            type: "selectWrapper",
            label: "Marital Status",
            placeHolder: "Select Marital Status",
            required: false,
            prevFocusField: "dateOfBirth",
            nextFocusField: "bloodGroup",
            className: "col-span-2",
            options: [
                {
                    label: "Single",
                    value: "single",
                },
                {
                    label: "Married",
                    value: "married",
                },
                {
                    label: "Divorced",
                    value: "divorced",
                },
                {
                    label: "Widowed",
                    value: "widowed",
                },
            ],
        },
        {
            id: "bloodGroup",
            type: "selectWrapper",
            label: "Blood Group",
            placeHolder: "Select Blood Group",
            required: false,
            prevFocusField: "maritalStatus",
            nextFocusField: "companyId",
            className: "col-span-2",
            options: [
                { label: "A+", value: "A+" },
                { label: "A-", value: "A-" },
                { label: "B+", value: "B+" },
                { label: "B-", value: "B-" },
                { label: "AB+", value: "AB+" },
                { label: "AB-", value: "AB-" },
                { label: "O+", value: "O+" },
                { label: "O-", value: "O-" },
            ],
        },
    ];

    const organizationInformationSchema = [
        {
            id: "companyId",
            type: "selectWrapper",
            label: "Company",
            placeHolder: "Select Company",
            required: true,
            prevFocusField: 'bloodGroup',
            nextFocusField: "branchId",
            className: "col-span-4",
            api: api + apiEndpoints.organization.company.CompanyHelp,
            labelKey: "companyName",
            valueKey: "_id",
        },
        {
            id: "branchId",
            type: "selectWrapper",
            label: "Branch",
            placeHolder: "Select Branch",
            required: true,
            prevFocusField: "companyId",
            nextFocusField: "departmentId",
            className: "col-span-4",
            api: api + apiEndpoints.organization.branch.BranchHelp,
            labelKey: "branchname",
            valueKey: "_id",
        },
        {
            id: "departmentId",
            type: "selectWrapper",
            label: "Department",
            placeHolder: "Select Department",
            required: true,
            prevFocusField: "branchId",
            nextFocusField: "designationId",
            className: "col-span-4",
            api: api + apiEndpoints.organization.department.DepartmentHelp,
            labelKey: "departmentname",
            valueKey: "_id",
        },
        {
            id: "designationId",
            type: "selectWrapper",
            label: "Designation",
            placeHolder: "Select Designation",
            required: true,
            prevFocusField: "departmentId",
            nextFocusField: "reportingManager",
            className: "col-span-4",
            api: api + apiEndpoints.organization.designation.DesignationHelp,
            labelKey: "designationname",
            valueKey: "_id",
        },
        {
            id: "reportingManager",
            type: "selectWrapper",
            label: "Reporting Manager",
            placeHolder: "Select Manager",
            required: false,
            prevFocusField: "designationId",
            nextFocusField: "employmentType",
            className: "col-span-4",
            api: api + apiEndpoints.employee.employee.EmployeeHelp,
            labelKey: "employeeName",
            valueKey: "_id",
        },
        {
            id: "employmentType",
            type: "selectWrapper",
            label: "Employment Type",
            placeHolder: "Select Employment Type",
            required: true,
            prevFocusField: "reportingManager",
            nextFocusField: "employeeStatus",
            className: "col-span-4",
            options: [
                { label: "Full Time", value: "FULL_TIME" },
                { label: "Part Time", value: "PART_TIME" },
                { label: "Contract", value: "CONTRACT" },
                { label: "Intern", value: "INTERN" },
            ],
        },
        {
            id: "employeeStatus",
            type: "selectWrapper",
            label: "Employee Status",
            placeHolder: "Select Status",
            required: true,
            prevFocusField: "employmentType",
            nextFocusField: "joiningDate",
            className: "col-span-4",
            options: [
                { label: "Active", value: "ACTIVE" },
                { label: "Inactive", value: "INACTIVE" },
                { label: "Notice Period", value: "NOTICE" },
            ],
        },
        {
            id: "joiningDate",
            type: "date",
            label: "Joining Date",
            required: true,
            prevFocusField: "employeeStatus",
            nextFocusField: "confirmationDate",
            className: "col-span-4",
        },
        {
            id: "confirmationDate",
            type: "date",
            label: "Confirmation Date",
            required: false,
            prevFocusField: "joiningDate",
            nextFocusField: "probationPeriod",
            className: "col-span-4",
        },
        {
            id: "probationPeriod",
            type: "selectWrapper",
            label: "Probation Period",
            placeHolder: "Select probationPeriod ",
            required: false,
            suffix: "Months",
            prevFocusField: "confirmationDate",
            nextFocusField: 'officialEmail',
            className: "col-span-4",
            options: [
                { label: "No Probation", value: 0 },
                { label: "1 Month", value: 1 },
                { label: "2 Months", value: 2 },
                { label: "3 Months", value: 3 },
                { label: "4 Months", value: 4 },
                { label: "6 Months", value: 5 },
                { label: "12 Months", value: 6 },
            ],
        },
    ];

    const contactInformationSchema = [
        {
            id: "officialEmail",
            type: "email",
            label: "Official Email",
            placeHolder: "e.g. john.doe@company.com",
            required: true,
            prevFocusField: 'probationPeriod',
            nextFocusField: "personalEmail",
            className: "col-span-4",
        },
        {
            id: "personalEmail",
            type: "email",
            label: "Personal Email",
            placeHolder: "e.g. john@gmail.com",
            required: true,
            prevFocusField: "officialEmail",
            nextFocusField: "mobileNumber",
            className: "col-span-4",
        },
        {
            id: "mobileNumber",
            type: "phone",
            label: "Mobile Number",
            placeHolder: "Enter Mobile Number",
            required: true,
            prevFocusField: "personalEmail",
            nextFocusField: "alternateMobile",
            className: "col-span-4",
        },
        {
            id: "alternateMobile",
            type: "phone",
            label: "Alternate Mobile",
            placeHolder: "Enter Alternate Mobile",
            required: false,
            prevFocusField: "mobileNumber",
            nextFocusField: "emergencyContactName",
            className: "col-span-4",
        },
        {
            id: "emergencyContactName",
            type: "text",
            label: "Emergency Contact Name",
            placeHolder: "Full Name",
            required: true,
            prevFocusField: "alternateMobile",
            nextFocusField: "emergencyContactNumber",
            className: "col-span-4",
        },
        {
            id: "emergencyContactNumber",
            type: "phone",
            label: "Emergency Contact Number",
            placeHolder: "Enter Contact Number",
            required: true,
            prevFocusField: "emergencyContactName",
            nextFocusField: "countryId",
            className: "col-span-4",
        },
        {
            id: "countryId",
            type: "selectWrapper",
            label: "Country",
            placeHolder: "Select Country",
            required: true,
            prevFocusField: "emergencyContactNumber",
            nextFocusField: "stateId",
            className: "col-span-4",
            api: api + apiEndpoints.master.country.CountryHelp,
            labelKey: "countryName",
            valueKey: "_id",
        },
        {
            id: "stateId",
            type: "selectWrapper",
            label: "State",
            placeHolder: "Select State",
            required: true,
            prevFocusField: "countryId",
            nextFocusField: "cityId",
            className: "col-span-4",
            api: api + apiEndpoints.master.state.StateHelp,
            labelKey: "stateName",
            valueKey: "_id",
        },
        {
            id: "cityId",
            type: "selectWrapper",
            label: "City",
            placeHolder: "Select City",
            required: true,
            prevFocusField: "stateId",
            nextFocusField: "postalCode",
            className: "col-span-4",
            api: api + apiEndpoints.master.city.CityHelp,
            labelKey: "cityName",
            valueKey: "_id",
        },
        {
            id: "postalCode",
            type: "text",
            label: "Postal Code",
            placeHolder: "380001",
            required: true,
            prevFocusField: "cityId",
            nextFocusField: "currentAddress",
            className: "col-span-4",
            maxLength: 10,
        },
        {
            id: "currentAddress",
            type: "text",
            label: "Current Address",
            placeHolder: "Enter Full Address",
            required: true,
            prevFocusField: "postalCode",
            nextFocusField: "aadhaarNumber",
            className: "col-span-8",
            rows: 3,
        },
    ];

    const documentInformationSchema = [
        {
            id: "aadhaarNumber",
            type: "text",
            label: "Aadhaar Number",
            placeHolder: "Enter 12 digit Aadhaar",
            required: true,
            className: "col-span-3",
            maxLength: 12,
            prevFocusField: "currentAddress",
            nextFocusField: "panNumber",
        },
        {
            id: "panNumber",
            type: "text",
            label: "PAN Number",
            placeHolder: "Enter PAN",
            required: true,
            className: "col-span-3",
            maxLength: 10,
            textTransform: "uppercase",
            prevFocusField: "aadhaarNumber",
            nextFocusField: "passportNumber",
        },
        {
            id: "passportNumber",
            type: "text",
            label: "Passport Number",
            placeHolder: "Enter Passport Number",
            className: "col-span-3",
            prevFocusField: "panNumber",
            nextFocusField: "drivingLicenseNumber",
        },
        {
            id: "drivingLicenseNumber",
            type: "text",
            label: "Driving License Number",
            placeHolder: "Enter DL Number",
            className: "col-span-3",
            prevFocusField: "passportNumber",
            nextFocusField: "bankName",
        },
    ];

    const payrollInformationSchema = [
        // Bank Details
        {
            id: "bankName",
            type: "selectWrapper",
            label: "Bank Name",
            placeHolder: "Select Bank",
            required: true,
            className: "col-span-4",
            api: api + apiEndpoints.master.bank.BankHelp,
            labelKey: "bankName",
            valueKey: "_id",
            prevFocusField: "drivingLicenseNumber",
            nextFocusField: "accountNumber",
        },
        {
            id: "accountNumber",
            type: "text",
            label: "Account Number",
            placeHolder: "Enter Account Number",
            required: true,
            className: "col-span-4",
            prevFocusField: "bankName",
            nextFocusField: "ifscCode",
        },
        {
            id: "ifscCode",
            type: "text",
            label: "IFSC / SWIFT Code",
            placeHolder: "Enter IFSC",
            required: true,
            className: "col-span-4",
            textTransform: "uppercase",
            prevFocusField: "accountNumber",
            nextFocusField: "uanNumber",
        },
        {
            id: "uanNumber",
            type: "text",
            label: "UAN Number (PF)",
            placeHolder: "Enter UAN",
            className: "col-span-4",
            prevFocusField: "ifscCode",
            nextFocusField: "pfNumber",
        },
        {
            id: "pfNumber",
            type: "text",
            label: "PF Number",
            placeHolder: "Enter PF Number",
            className: "col-span-4",
            prevFocusField: "uanNumber",
            nextFocusField: "esiNumber",
        },
        {
            id: "esiNumber",
            type: "text",
            label: "ESI Number",
            placeHolder: "Enter ESI Number",
            className: "col-span-4",
            prevFocusField: "pfNumber",
            nextFocusField: "salaryStructure",
        },

        // Compensation
        {
            id: "salaryStructure",
            type: "selectWrapper",
            label: "Salary Structure",
            placeHolder: "Select Structure",
            required: true,
            className: "col-span-4",
            prevFocusField: "esiNumber",
            nextFocusField: "ctc",
            options: [
                { label: "Monthly Fixed Salary", value: "monthly_fixed" },
                { label: "Monthly + Performance Incentive", value: "monthly_incentive" },
                { label: "Hourly Salary", value: "hourly" },
                { label: "Daily Wage", value: "daily_wage" },
                { label: "Annual CTC", value: "annual_ctc" },
            ],
        },
        {
            id: "ctc",
            type: "number",
            label: "CTC (Annual)",
            placeHolder: "0",
            required: true,
            className: "col-span-4",
            prevFocusField: "salaryStructure",
            nextFocusField: "basicSalary",
        },
        {
            id: "basicSalary",
            type: "number",
            label: "Basic Salary (Monthly)",
            placeHolder: "0",
            required: true,
            className: "col-span-4",
            prevFocusField: "ctc",
            nextFocusField: "username",
        },
    ];

    const accessInformationSchema = [
        // User Credentials
        {
            id: "username",
            type: "text",
            label: "Username",
            placeHolder: "e.g. john@company.com",
            required: true,
            className: "col-span-4",
            nextFocusField: "password",
            prevFocusField: "basicSalary",

        },
        {
            id: "password",
            type: "text",
            inputType: "password",
            label: "Password",
            placeHolder: "Generate Password",
            required: true,
            className: "col-span-4",
            isGeneratePassword: true,
            prevFocusField: "username",
            nextFocusField: "primaryRole",
        },

        // Access Control
        {
            id: "primaryRole",
            type: "selectWrapper",
            label: "Primary Role",
            placeHolder: "Select Role",
            required: true,
            className: "col-span-4",
            prevFocusField: "password",
            nextFocusField: "userGroup",
            options: [
                {
                    label: "Standard Employee",
                    value: "EMPLOYEE",
                },
                {
                    label: "Manager",
                    value: "MANAGER",
                },
                {
                    label: "HR",
                    value: "HR",
                },
                {
                    label: "Administrator",
                    value: "ADMIN",
                },
            ],
        },
        {
            id: "userGroup",
            type: "selectWrapper",
            label: "User Group",
            placeHolder: "Select Group",
            required: true,
            className: "col-span-4",
            prevFocusField: "primaryRole",
            nextFocusField: "userGroup",
            options: [
                {
                    label: "Product Development",
                    value: 1,
                },
                {
                    label: "Finance",
                    value: 2,
                },
                {
                    label: "Human Resource",
                    value: 3,
                },
            ],
        },
    ];

    const reviewInformationSchema = [];

    return {
        employeeListingColDef,
        personalInformationSchema,
        organizationInformationSchema,
        contactInformationSchema,
        documentInformationSchema,
        payrollInformationSchema,
        accessInformationSchema,
        reviewInformationSchema,
    };
};

export default useEmployeeConfig;